spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/assign-item
    username: root
    password: P4ssw0rd
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      name: user-service
      profile: default

server:
  port: 8030

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka