spring:
  application:
    name: grocery-bill-service
  datasource:
    url: jdbc:mysql://localhost:3306/assign-grocery-bill
    username: root
    password: P4ssw0rd
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka