spring:
  application:
    name: grocery-bill-service
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_URI:localhost}:3306/assign-grocery-bill
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:P4ssw0rd}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8050

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${NAMING_SERVER_URI:http://localhost}:8761/eureka

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health