spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_URI:localhost}:3306/assign-user
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:P4ssw0rd}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
# Uncomment when running configServer app
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: config-server
#      name: user-service
#      profile: default

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health


server:
  port: 8020

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${NAMING_SERVER_URI:http://localhost}:8761/eureka

user-service:
  secretKey: grocerybillapp
