spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/assign-user
    username: root
    password: P4ssw0rd
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      name: user-service
      profile: default

management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka
