spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - Authorization
              - content-type
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      discovery:
        locator: enabled
      routes:
        - id: service-user-id
          uri: lb://user-service
          predicates:
            Path=/api/v1/users/**
        - id: service-grocerybill-id
          uri: lb://grocery-bill-service
          predicates:
            Path=/api/v1/bills/**
          filters:
            - AuthFilter
            - RoleFilter
        - id: service-item-id
          uri: lb://item-service
          predicates:
            Path=/api/v1/items/**
          filters:
            - AuthFilter
            - RoleFilter

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 8080
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka