# pull official base image
FROM node:17.8.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json /app
COPY package-lock.json /app
RUN npm install react-scripts@5.0.0 -g --silent
RUN npm install --silent

# add app
COPY . ./

# expose port
EXPOSE 3000

# start app
CMD ["npm", "start"]