// item related
export const FETCH_ITEMS_BEGIN = "FETCH_ITEMS_BEGIN";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILED = "FETCH_ITEMS_FAILED";
export const EDIT_ITEM_BEGIN = "EDIT_ITEM_BEGIN";
export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const EDIT_ITEM_FAILED = "EDIT_ITEM_FAILED";
export const DELETE_ITEM_BEGIN = "EDIT_ITEM_BEGIN";
export const DELETE_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const DELETE_ITEM_FAILED = "EDIT_ITEM_FAILED";
export const UPDATE_ITEM_SELECTED = "UPDATE_ITEM_SELECTED";
export const RESET_ITEM_LIST = "RESET_ITEM_LIST";
export const RESET_ITEM_STATES = "RESET_ITEM_STATES";

// user related
export const CREATE_USER_BEGIN = "CREATE_USER_BEGIN";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const FETCH_USERS_BEGIN = "FETCH_USERS_BEGIN";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";
export const EDIT_USER_BEGIN = "EDIT_USER_BEGIN";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SELECTED = "UPDATE_USER_SELECTED";
export const RESET_USER_LIST = "RESET_USER_LIST";
export const RESET_USER_STATES = "RESET_USER_STATES";

// Authentication action types
export const CREATE_JWT = "CREATE_JWT";
export const FETCH_JWT_BEGIN = "FETCH_JWT_BEGIN";
export const FETCH_JWT_SUCCESS = "FETCH_JWT_SUCCESS";
export const FETCH_JWT_FAILED = "FETCH_JWT_FAILED";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const RESET_AUTH_STATES = "RESET_AUTH_STATES";

// Bill action types
export const FETCH_BILLS_BEGIN = "FETCH_BILLS_BEGIN";
export const FETCH_BILLS_FAILED = "FETCH_BILLS_FAILED";
export const FETCH_BILLS_SUCCESS = "FETCH_BILLS_SUCCESS";
export const CREATE_BILL_BEGIN = "CREATE_BILL_BEGIN";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAILED = "CREATE_BILL_FAILED";
export const UPDATE_CURRENT_BILL = "UPDATE_CURRENT_BILL";
export const ADD_ON_HOLD_BILL = "ADD_ON_HOLD_BILL";
export const ADD_ITEM_ON_CURRENT_BILL = "ADD_ITEM_ON_CURRENT_BILL";
export const REMOVE_ITEM_ON_CURRENT_BILL = "REMOVE_ITEM_ON_CURRENT_BILL";
export const UPDATE_ITEM_IN_CURRENT_BILL = "UPDATE_ITEM_COUNT_IN_CURRENT_BILL";
export const CHANGE_CURRENT_BILL = "CHANGE_CURRENT_BILL";
export const UPDATE_CURRENT_BILL_TYPE = "UPDATE_CURRENT_BILL_TYPE";
export const UPDATE_BILL_SELECTED = "UPDATE_BILL_SELECTED";
export const RESET_BILL_LIST = "RESET_BILL_LIST";
export const RESET_CURRENT_BILL = "RESET_CURRENT_BILL";
export const RESET_BILL_STATES = "RESET_BILL_STATES";

// Modal action types
export const SET_MODAL_COMPONENT = "SET_MODAL_COMPONENT";
export const SET_BILL_COMPONENT = "SET_BILL_COMPONENT";
export const RESET_COMPONENT_STATES = "RESET_COMPONENT_STATES";
